APP:
  PROJECT_NAME: Ecoverse APIs
  PROJECT_VERSION: 1.0.0
  ENVIRONMENT: !ENV ${ENVIRONMENT}
  DEBUG: False
  TESTING: False

DATABASE: # MSSQL database
  SERVER: !ENV ${SERVER}
  USERNAME: !ENV ${USERNAME}
  PASSWORD: !ENV ${PASSWORD}
  DATABASE: !ENV ${DATABASE}
